openapi: 3.0.4
info:
  title: Favorite Game Gauntlet
  version: 0.14.0
paths:
  /points/{login}/info:
    get:
      operationId: getUserPointInfo
      tags:
        - Points
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/PointInfoResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /points/all/info:
    get:
      operationId: getAllPointInfo
      tags:
        - Points
      responses:
        '200':
          $ref: '#/components/responses/PointInfoByLoginsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /points/{login}/territory-points:
    post:
      operationId: changeUserTerritoryPoints
      tags:
        - Points
      parameters:
        - $ref: '#/components/parameters/Login'
      requestBody:
        $ref: '#/components/requestBodies/PointChangeRequest'
      responses:
        '200':
          $ref: '#/components/responses/TerritoryPointChangeResultResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    get:
      operationId: getUserTerritoryPoints
      tags:
        - Points
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/PointsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /points/{login}/territory-points/history:
    get:
      operationId: getUserTerritoryPointHistory
      tags:
        - Points
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/TerritoryPointChangeHistoriesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /points/{login}/free-points:
    post:
      operationId: changeFreePoints
      tags:
        - Points
      parameters:
        - $ref: '#/components/parameters/Login'
      requestBody:
        $ref: '#/components/requestBodies/FreePointChangeRequest'
      responses:
        '200':
          $ref: '#/components/responses/FreePointChangeResultResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    get:
      operationId: getFreePoints
      tags:
        - Points
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/PointsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /points/{login}/free-points/history:
    get:
      operationId: getUserFreePointHistory
      tags:
        - Points
      parameters:
        - $ref: '#/components/parameters/Login'
      responses:
        '200':
          $ref: '#/components/responses/FreePointChangeHistoriesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /points/experience-points:
    post:
      operationId: changeExperiencePoints
      tags:
        - Points
      requestBody:
        $ref: '#/components/requestBodies/PointChangeRequest'
      responses:
        '200':
          $ref: '#/components/responses/PointChangeResultResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    get:
      operationId: getExperiencePoints
      tags:
        - Points
      responses:
        '200':
          $ref: '#/components/responses/PointsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /points/territory-hours:
    post:
      operationId: changeTerritoryHours
      tags:
        - Points
      requestBody:
        $ref: '#/components/requestBodies/TerritoryHourChangeRequest'
      responses:
        '200':
          $ref: '#/components/responses/PointChangeResultByTypesResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    get:
      operationId: getTerritoryHours
      tags:
        - Points
      responses:
        '200':
          $ref: '#/components/responses/PointsResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    Login:
      type: string
      pattern: ^\w+$
      minLength: 3
      maxLength: 35
    Points:
      type: integer
      format: int
      minimum: 0
    PointInfo:
      type: object
      properties:
        territoryPoints:
          $ref: '#/components/schemas/Points'
        freePoints:
          $ref: '#/components/schemas/Points'
      required:
        - territoryPoints
        - freePoints
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    PointInfoByLogins:
      type: array
      items:
        type: object
        properties:
          login:
            $ref: '#/components/schemas/Login'
          pointInfo:
            $ref: '#/components/schemas/PointInfo'
    PointChange:
      type: object
      properties:
        changeSource:
          type: string
        desiredChangeValue:
          type: integer
          format: int
      required:
        - changeSource
        - desiredChangeValue
    PointChangeResult:
      type: object
      properties:
        actualChangeValue:
          type: integer
          format: int
        finalValue:
          $ref: '#/components/schemas/Points'
      required:
        - actualChangeValue
        - finalValue
    PointChangeHistoryRow:
      allOf:
        - $ref: '#/components/schemas/PointChange'
        - type: object
          properties:
            actualChangeValue:
              type: integer
              format: int
            finalValue:
              $ref: '#/components/schemas/Points'
          required:
            - actualChangeValue
            - finalValue
    TerritoryPointChangeHistory:
      allOf:
        - $ref: '#/components/schemas/PointChangeHistoryRow'
        - type: object
          properties:
            changeSource:
              enum:
                - territory-obtaining
                - territory-loss
                - other
            changeDate:
              type: string
              format: date-time
            sourceLogin:
              nullable: true
              example: null
              allOf:
                - $ref: '#/components/schemas/Login'
          required:
            - changeDate
      example:
        changeSource: territory-obtaining
        desiredChangeValue: 2
        actualChangeValue: 2
        finalValue: 12
        changeDate: '2026-06-07T08:09:10.123Z'
    TerritoryPointChangeHistories:
      type: array
      items:
        $ref: '#/components/schemas/TerritoryPointChangeHistory'
    Name:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 70
    FreePointChange:
      allOf:
        - $ref: '#/components/schemas/PointChange'
        - type: object
          properties:
            wheelEffectName:
              nullable: true
              example: null
              allOf:
                - $ref: '#/components/schemas/Name'
    FreePointChangeHistory:
      allOf:
        - $ref: '#/components/schemas/PointChangeHistoryRow'
        - type: object
          properties:
            changeSource:
              enum:
                - wheel-effect
                - quest
                - base-teleport
                - sandstorm
                - other
            changeDate:
              type: string
              format: date-time
            sourceLogin:
              nullable: true
              example: null
              allOf:
                - $ref: '#/components/schemas/Login'
            wheelEffectName:
              nullable: true
              example: null
              allOf:
                - $ref: '#/components/schemas/Name'
          required:
            - changeDate
      example:
        actualChangeValue: 2
        changeSource: quest
        desiredChangeValue: 2
        finalValue: 12
        changeDate: '2026-06-07T08:09:10.123Z'
    FreePointChangeHistories:
      type: array
      items:
        $ref: '#/components/schemas/FreePointChangeHistory'
    TerritoryHourChange:
      allOf:
        - $ref: '#/components/schemas/PointChange'
        - type: object
          properties:
            isSomeones:
              type: boolean
              default: false
            login:
              nullable: true
              example: null
              allOf:
                - $ref: '#/components/schemas/Login'
    PointChangeResultByTypes:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PointChangeResult'
  parameters:
    Login:
      name: login
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Login'
  responses:
    PointInfoResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PointInfo'
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    PointInfoByLoginsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PointInfoByLogins'
    PointsResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Points'
    TerritoryPointChangeResultResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PointChangeResult'
    TerritoryPointChangeHistoriesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TerritoryPointChangeHistories'
          example:
            - changeSource: territory-obtaining
              desiredChangeValue: 2
              actualChangeValue: 2
              finalValue: 12
              changeDate: '2026-06-07T08:09:10.123Z'
    FreePointChangeResultResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PointChangeResult'
    FreePointChangeHistoriesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FreePointChangeHistories'
          example:
            - changeSource: quest
              desiredChangeValue: 2
              actualChangeValue: 2
              finalValue: 12
              changeDate: '2026-06-07T08:09:10.123Z'
    PointChangeResultResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PointChangeResult'
    PointChangeResultByTypesResponse:
      description: Success.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PointChangeResultByTypes'
  requestBodies:
    PointChangeRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PointChange'
    FreePointChangeRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FreePointChange'
    TerritoryHourChangeRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TerritoryHourChange'
